name: "Deploy para VPS"
on:
  push:
    branches:
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Baixar o código"
        uses: actions/checkout@v4

      - name: "Copiar arquivos para VPS"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "82.112.244.66"
          username: "root"
          password: ${{ secrets.PASSWORD_VP }}
          source: "."
          target: "/application"

      - name: "Build da aplicação"
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: "82.112.244.66"
          username: "root"
          password: ${{ secrets.PASSWORD_VP }}
          script: |
            cd /application
            composer install --no-dev --no-progress -a
            php artisan optimize
            chown -R www-data:www-data .
